substitutions:

  ####
  # RTTTL Sounds
  ominous_warning: 'ominous:d=4,o=6,b=160:16e,16f,16g,16f,16e,16f,16g,16f,16e,16f,16g,16f,16e,16f,16g,16f,16e,16f,16g,16f,16e,16f,16g,16f,16e,16f,16g,16f,16e,16f,16g,16f,16e,16f,16g,16f,16e,16f,16g,16f'
  charming_warning: 'charming:d=4,o=5,b=120:16e6,16f6,16g6,16a6,16b6,16a6,16g6,16f6,16e6,16d6,16c6,16b5,16c6,16d6,16e6,16f6'
  star_wars: 'star_wars:d=16,o=5,b=100:4e,4e,4e,8c,p,g,4e,8c,p,g,4e,4p,4b,4b,4b,8c6,p,g,4d#,8c,p,g,4e,8p'
  mario: 'mario:d=4,o=5,b=100:16e6,16e6,32p,8e6,16c6,8e6,8g6,8p,8g,8p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,16p,8c6,16p,8g,16p,8e,16p,8a,8b,16a#,8a,16g.,16e6,16g6,8a6,16f6,8g6,8e6,16c6,16d6,8b,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16c7,16p,16c7,16c7,p,16g6,16f#6,16f6,16d#6,16p,16e6,16p,16g#,16a,16c6,16p,16a,16c6,16d6,8p,16d#6,8p,16d6,8p,16c6'
  mission_impossible: 'MissionImp:d=16,o=6,b=95:32d,32d#,32d,32d#,32d,32d#,32d,32d#,32d,32d,32d#,32e,32f,32f#,32g,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,g,8p,g,8p,a#,p,c7,p,g,8p,g,8p,f,p,f#,p,a#,g,2d,32p,a#,g,2c#,32p,a#,g,2c,a#5,8c,2p,32p,a#5,g5,2f#,32p,a#5,g5,2f,32p,a#5,g5,2e,d#,8d'
  urgent: 'Urgent:d=8,o=6,b=500:c,e,d7,c,e,a#,c,e,a,c,e,g,c,e,a,c,e,a#,c,e,d7'
  scale_up: 'scale_up:d=32,o=5,b=100:c,c#,d#,e,f#,g#,a#,b'
  mosaic_1: 'Mosaic:d=8,o=6,b=400:c,e,g,e,c,g,e,g,c,g,c,e,c,g,e,g,e,c'
  mosiac_2: 'Mosaic:d=8,o=6,b=400:c,e,g,e,c,g,e,g,c,g,c,e,c,g,e,g,e,c,p,c5,e5,g5,e5,c5,g5,e5,g5,c5,g5,c5,e5,c5,g5,e5,g5,e5,c5'
  success_beep: 'success:d=24,o=5,b=100:c,g,b'

output:
  - platform: esp8266_pwm
    pin: $warning_beep_pin
    id: rtttl_out

rtttl:
  output: rtttl_out

button:  
  - platform: template
    id: warning_tone
    name: "Play Warning"
    internal: true
    on_press:
      then:
        - rtttl.play: $ominous_warning

  - platform: template
    id: star_wars_tone
    name: "Play Star Wars"
    internal: true
    on_press:
      then:
        - rtttl.play: $star_wars

  - platform: template
    id: mario_tone
    name: "Play Mario"
    internal: true
    on_press:
      then:
        - rtttl.play: $mario

  - platform: template
    id: mi_tone
    name: "Play Mission Impossible"
    internal: true
    on_press:
      then:
        - rtttl.play: $mission_impossible
